source: .
branch: True
ignore:
  - */tests/*
  - */management/*
  - */migrations/*
  - venv/*
  -.venv/*
  - */wsgi.py
  - */asgi.py
  - manage.py

codecov:
  token: "7cfb8809-743c-4771-8931-ea69b67f8b97"