# Generated by Django 4.2.16 on 2025-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityGrants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, help_text='Link to Opportunity Grant', max_length=512)),
                ('is_open', models.BooleanField(default=False, help_text='Whether the button is an open state.')),
                ('closing_date', models.DateTimeField(blank=True, help_text='The date and time when the button should be considered closed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the Opportunity Grant was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the Opportunity Grant was updated.')),
            ],
            options={
                'verbose_name': 'Opportunity Grant',
            },
        ),
    ]
