# Generated by Django 4.2.16 on 2025-01-05 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='A Description of the file.')),
                ('item', models.FileField(upload_to='sponsors_files')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='The name of the sponsorship package.', max_length=255)),
                ('number_available', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='$', help_text='Currency symbol of the sponsorship package.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of the sponsorship package.', max_digits=12)),
                ('short_description', models.TextField(help_text='A short description of the sponsorship package.')),
                ('files', models.ManyToManyField(blank=True, help_text='The files of the sponsorship package.', related_name='packages', to='sponsors.sponsorshipfile')),
            ],
            options={
                'ordering': ['order', '-amount', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='A description of the sponsor.')),
                ('url', models.URLField(blank=True, default='', help_text='The URL of the sponsor if needed.')),
                ('packages', models.ManyToManyField(related_name='sponsors', to='sponsors.sponsorshippackage')),
            ],
            options={
                'ordering': ['order', 'name', 'id'],
            },
        ),
    ]
