# Generated by Django 4.2.16 on 2025-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_rename_sponsorshipfile_file_taggedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='hiring',
            field=models.BooleanField(default=False, help_text='Whether the sponsor is hiring or not.'),
        ),
    ]
