# Generated by Django 4.2.16 on 2025-01-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_sponsor_hiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshippackage',
            name='symbol',
            field=models.CharField(blank=True, help_text='The symbol of the sponsorship package.', max_length=1),
        ),
    ]
