# Generated by Django 4.2.16 on 2025-01-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_alter_sponsorshippackage_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='hiring_url',
            field=models.URLField(blank=True, default='', help_text='Hiring URL of the sponsor.'),
        ),
    ]
