# Generated by Django 4.2.13 on 2024-12-10 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('hard_no', models.BooleanField(default=False)),
                ('favourite', models.BooleanField(default=False)),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('data_type', models.CharField(choices=[('true/false', 'true/false'), ('score', 'score')])),
                ('minimum_score', models.SmallIntegerField(default=0)),
                ('maximum_score', models.SmallIntegerField(default=5)),
                ('help_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAspectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proposals.reviewaspect')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposals.review')),
            ],
        ),
    ]
