# Generated by Django 4.2.13 on 2024-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_review_reviewaspect_reviewaspectscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewaspectscore',
            name='bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewaspectscore',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewaspect',
            name='maximum_score',
            field=models.SmallIntegerField(default=4),
        ),
    ]
