# Generated by Django 5.0 on 2025-07-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_check_in',
            field=models.BooleanField(default=False, help_text='Whether this is a check-in session'),
        ),
    ]
