# Generated by Django 5.0 on 2025-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_session_is_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('keynote', 'Keynote'), ('talk', 'Talk'), ('workshop', 'Workshop'), ('panel', 'Panel'), ('break', 'Break'), ('check-in', 'Check-in')], default='talk', help_text='Type of session', max_length=20),
        ),
    ]
