# Generated by Django 5.0 on 2025-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_session_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_closing',
            field=models.BooleanField(default=False, help_text='Whether this is a closing session'),
        ),
        migrations.AddField(
            model_name='session',
            name='is_opening',
            field=models.BooleanField(default=False, help_text='Whether this is a opening session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('keynote', 'Keynote'), ('talk', 'Talk'), ('workshop', 'Workshop'), ('panel', 'Panel'), ('break', 'Break'), ('check-in', 'Check-in'), ('is-opening', 'Is opening'), ('is-closing', 'Is closing')], default='talk', help_text='Type of session', max_length=20),
        ),
    ]
