# Generated by Django 5.0 on 2025-07-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_session_is_closing_session_is_opening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name', max_length=255)),
            ],
            options={
                'verbose_name': 'Tracks',
                'verbose_name_plural': 'Tracks',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='track',
            field=models.ForeignKey(help_text='Session track', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.tracks'),
        ),
    ]
