# Generated by Django 5.0 on 2025-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_tracks_session_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('keynote', 'Keynote'), ('talk', 'Talk'), ('lighting', 'Lighting Talk'), ('workshop', 'Workshop'), ('panel', 'Panel'), ('break', 'Break'), ('check-in', 'Check-in'), ('is-opening', 'Opening'), ('is-closing', 'Closing')], default='talk', help_text='Type of session', max_length=20),
        ),
        migrations.RemoveField(
            model_name='session',
            name='speaker',
        ),
        migrations.AddField(
            model_name='session',
            name='speaker',
            field=models.ManyToManyField(blank=True, help_text='Session speakers', related_name='speakers', to='schedule.speaker'),
        ),
    ]
