# Generated by Django 5.0 on 2025-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_session_session_type_remove_session_speaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('keynote', 'Keynote'), ('talk', 'Talk'), ('lighting', 'Lighting Talk'), ('workshop', 'Workshop'), ('panel', 'Panel'), ('break', 'Break')], default='talk', help_text='Type of session', max_length=20),
        ),
    ]
