# Generated by Django 5.0 on 2025-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('keynote', 'Keynote'), ('talk', 'Talk'), ('lighting', 'Lighting Talk'), ('workshop', 'Workshop'), ('panel', 'Panel'), ('break', 'Break'), ('sprints', 'Sprints')], default='talk', help_text='Type of session', max_length=20),
        ),
    ]
