# Generated by Django 5.0 on 2025-07-26 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_session_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Session track', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.tracks'),
        ),
    ]
