# Generated by Django 4.2.13 on 2024-12-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reviewer',
            field=models.BooleanField(default=False, verbose_name='is reviewer'),
        ),
    ]
