name: Ruff

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff
      run: ruff check --output-format=github .